/*
 * Copyright 2019-2020 NXP.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: LPC54018
package_id: LPC54018JET180
mcu_data: ksdk2_0
processor_version: 7.0.1
pin_labels:
- {pin_num: A13, pin_signal: PIO3_3/LCD_VD(17)/FC9_TXD_SCL_MISO, label: PWRON, identifier: PWRON}
- {pin_num: E3, pin_signal: PIO3_14/SCT0_OUT4/FC9_RTS_SCL_SSEL1/CTIMER3_MAT1/TRACEDATA(2), label: KFFET, identifier: KFFET}
- {pin_num: H4, pin_signal: PIO3_13/SCT0_OUT9/FC9_CTS_SDA_SSEL0/CTIMER3_CAP1/EMC_FBCK/TRACEDATA(1), label: LED, identifier: LED}
- {pin_num: B10, pin_signal: PIO3_5/LCD_VD(19)/FC8_RTS_SCL_SSEL1/CTIMER4_MAT1, label: PWRON, identifier: LCD_VD19}
- {pin_num: N3, pin_signal: PIO1_0/FC0_RTS_SCL_SSEL1/SD_D(3)/CTIMER0_CAP2/SCT0_GPI4/TRACECLK/ADC0_6, label: IRQ, identifier: IRQ}
- {pin_num: P11, pin_signal: PIO1_22/FC8_RTS_SCL_SSEL1/SD_CMD/CTIMER2_MAT3/SCT0_GPI5/FC4_SSEL3/EMC_CKE(1), label: IRQ, identifier: IRQ}
- {pin_num: C10, pin_signal: PIO3_2/LCD_VD(16)/FC9_RXD_SDA_MOSI/CTIMER1_MAT2, label: IRQ, identifier: IRQ}
- {pin_num: A3, pin_signal: PIO3_10/SCT0_OUT3/CTIMER3_MAT0/EMC_DYCSN(1)/TRACEDATA(0), label: PWRON, identifier: PWRON}
- {pin_num: A14, pin_signal: PIO4_7/CTIMER4_CAP3/USB0_PORTPWRN/USB0_FRAME/SCT0_GPI0, label: PWRON, identifier: PWRON}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iocon.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/

#define IOCON_PIO_DIGITAL_EN        0x0100u   /*!< Enables digital function */
#define IOCON_PIO_FUNC0               0x00u   /*!< Selects pin function 0 */
#define IOCON_PIO_FUNC1               0x01u   /*!< Selects pin function 1 */
#define IOCON_PIO_INPFILT_OFF       0x0200u   /*!< Input filter disabled */
#define IOCON_PIO_INPFILT_ON          0x00u   /*!< Input filter enabled */
#define IOCON_PIO_INV_DI              0x00u   /*!< Input function is not inverted */
#define IOCON_PIO_MODE_INACT          0x00u   /*!< No addition pin function */
#define IOCON_PIO_MODE_PULLUP         0x20u   /*!< Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI        0x00u   /*!< Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD       0x00u   /*!< Standard mode, output slew rate control is enabled */
#define PIN0_IDX                         0u   /*!< Pin number for pin 0 in a port 3 */
#define PIN1_IDX                         1u   /*!< Pin number for pin 1 in a port 3 */
#define PIN5_IDX                         5u   /*!< Pin number for pin 5 in a port 3 */
#define PIN6_IDX                         6u   /*!< Pin number for pin 6 in a port 3 */
#define PIN7_IDX                         7u   /*!< Pin number for pin 7 in a port 3 */
#define PIN8_IDX                         8u   /*!< Pin number for pin 8 in a port 3 */
#define PIN9_IDX                         9u   /*!< Pin number for pin 9 in a port 3 */
#define PIN11_IDX                       11u   /*!< Pin number for pin 11 in a port 2 */
#define PIN13_IDX                       13u   /*!< Pin number for pin 13 in a port 2 */
#define PIN14_IDX                       14u   /*!< Pin number for pin 14 in a port 2 */
#define PIN15_IDX                       15u   /*!< Pin number for pin 15 in a port 2 */
#define PIN16_IDX                       16u   /*!< Pin number for pin 16 in a port 2 */
#define PIN21_IDX                       21u   /*!< Pin number for pin 21 in a port 2 */
#define PIN22_IDX                       22u   /*!< Pin number for pin 22 in a port 2 */
#define PIN23_IDX                       23u   /*!< Pin number for pin 23 in a port 2 */
#define PIN24_IDX                       24u   /*!< Pin number for pin 24 in a port 2 */
#define PIN25_IDX                       25u   /*!< Pin number for pin 25 in a port 2 */
#define PIN28_IDX                       28u   /*!< Pin number for pin 28 in a port 2 */
#define PIN29_IDX                       29u   /*!< Pin number for pin 29 in a port 0 */
#define PIN30_IDX                       30u   /*!< Pin number for pin 30 in a port 0 */
#define PIN31_IDX                       31u   /*!< Pin number for pin 31 in a port 2 */
#define PORT0_IDX                        0u   /*!< Port index */
#define PORT2_IDX                        2u   /*!< Port index */
#define PORT3_IDX                        3u   /*!< Port index */


void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: B12, peripheral: USBFSH, signal: USB_VBUS, pin_signal: PIO0_22/FC6_TXD_SCL_MISO_WS/UTICK_CAP1/CTIMER3_CAP3/SCT0_OUT3/USB0_VBUS, mode: inactive, invert: disabled,
    slew_rate: standard, open_drain: disabled}
  - {pin_num: B13, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI, pin_signal: PIO0_29/FC0_RXD_SDA_MOSI/CTIMER2_MAT3/SCT0_OUT8/TRACEDATA(2), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
  - {pin_num: A2, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO, pin_signal: PIO0_30/FC0_TXD_SCL_MISO/CTIMER0_MAT0/SCT0_OUT9/TRACEDATA(1), mode: inactive, invert: disabled,
    glitch_filter: disabled, slew_rate: standard, open_drain: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitPins(void)
{
    /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
    //CLOCK_EnableClock(kCLOCK_Iocon);

	 CLOCK_EnableClock(kCLOCK_Iocon);                           /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */

	  const uint32_t port0_pin29_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as FC0_RXD_SDA_MOSI */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT0_IDX, PIN29_IDX, port0_pin29_config); /* PORT0 PIN29 (coords: B13) is configured as FC0_RXD_SDA_MOSI */
	  const uint32_t port0_pin30_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as FC0_TXD_SCL_MISO */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT0_IDX, PIN30_IDX, port0_pin30_config); /* PORT0 PIN30 (coords: A2) is configured as FC0_TXD_SCL_MISO */
	  const uint32_t port2_pin11_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_PWR */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN11_IDX, port2_pin11_config); /* PORT2 PIN11 (coords: K3) is configured as LCD_PWR */
	  const uint32_t port2_pin13_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_DCLK */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN13_IDX, port2_pin13_config); /* PORT2 PIN13 (coords: P7) is configured as LCD_DCLK */
	  const uint32_t port2_pin14_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_FP */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN14_IDX, port2_pin14_config); /* PORT2 PIN14 (coords: L7) is configured as LCD_FP */
	  const uint32_t port2_pin15_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_AC */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN15_IDX, port2_pin15_config); /* PORT2 PIN15 (coords: M8) is configured as LCD_AC */
	  const uint32_t port2_pin16_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_LP */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN16_IDX, port2_pin16_config); /* PORT2 PIN16 (coords: L8) is configured as LCD_LP */
	  const uint32_t port2_pin21_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(3) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN21_IDX, port2_pin21_config); /* PORT2 PIN21 (coords: L10) is configured as LCD_VD(3) */
	  const uint32_t port2_pin22_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(4) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN22_IDX, port2_pin22_config); /* PORT2 PIN22 (coords: K10) is configured as LCD_VD(4) */
	  const uint32_t port2_pin23_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(5) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN23_IDX, port2_pin23_config); /* PORT2 PIN23 (coords: M14) is configured as LCD_VD(5) */
	  const uint32_t port2_pin24_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(6) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN24_IDX, port2_pin24_config); /* PORT2 PIN24 (coords: K14) is configured as LCD_VD(6) */
	  const uint32_t port2_pin25_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(7) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN25_IDX, port2_pin25_config); /* PORT2 PIN25 (coords: J11) is configured as LCD_VD(7) */
	  const uint32_t port2_pin28_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(10) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN28_IDX, port2_pin28_config); /* PORT2 PIN28 (coords: G13) is configured as LCD_VD(10) */
	  const uint32_t port2_pin29_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(11) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN29_IDX, port2_pin29_config); /* PORT2 PIN29 (coords: G11) is configured as LCD_VD(11) */
	  const uint32_t port2_pin30_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(12) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN30_IDX, port2_pin30_config); /* PORT2 PIN30 (coords: F12) is configured as LCD_VD(12) */
	  const uint32_t port2_pin31_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(13) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT2_IDX, PIN31_IDX, port2_pin31_config); /* PORT2 PIN31 (coords: D14) is configured as LCD_VD(13) */
	  const uint32_t port3_pin0_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(14) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN0_IDX, port3_pin0_config); /* PORT3 PIN0 (coords: D12) is configured as LCD_VD(14) */
	  const uint32_t port3_pin1_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(15) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN1_IDX, port3_pin1_config); /* PORT3 PIN1 (coords: D11) is configured as LCD_VD(15) */
	  const uint32_t port3_pin31_config = (
	    IOCON_PIO_FUNC0 |                                        /* Pin is configured as PIO3_31 */
	    IOCON_PIO_MODE_PULLUP |                                  /* Selects pull-up function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_ON |                                   /* Input filter enabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN31_IDX, port3_pin31_config); /* PORT3 PIN31 (coords: J14) is configured as PIO3_31 */
	  const uint32_t port3_pin5_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(19) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN5_IDX, port3_pin5_config); /* PORT3 PIN5 (coords: B10) is configured as LCD_VD(19) */
	  const uint32_t port3_pin6_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(20) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN6_IDX, port3_pin6_config); /* PORT3 PIN6 (coords: C9) is configured as LCD_VD(20) */
	  const uint32_t port3_pin7_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(21) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN7_IDX, port3_pin7_config); /* PORT3 PIN7 (coords: B8) is configured as LCD_VD(21) */
	  const uint32_t port3_pin8_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(22) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN8_IDX, port3_pin8_config); /* PORT3 PIN8 (coords: A7) is configured as LCD_VD(22) */
	  const uint32_t port3_pin9_config = (
	    IOCON_PIO_FUNC1 |                                        /* Pin is configured as LCD_VD(23) */
	    IOCON_PIO_MODE_INACT |                                   /* No addition pin function */
	    IOCON_PIO_INV_DI |                                       /* Input function is not inverted */
	    IOCON_PIO_DIGITAL_EN |                                   /* Enables digital function */
	    IOCON_PIO_INPFILT_OFF |                                  /* Input filter disabled */
	    IOCON_PIO_SLEW_STANDARD |                                /* Standard mode, output slew rate control is enabled */
	    IOCON_PIO_OPENDRAIN_DI                                   /* Open drain is disabled */
	  );
	  IOCON_PinMuxSet(IOCON, PORT3_IDX, PIN9_IDX, port3_pin9_config); /* PORT3 PIN9 (coords: C7) is configured as LCD_VD(23) */


    IOCON->PIO[0][22] =
        ((IOCON->PIO[0][22] &
          /* Mask bits to zero which are setting */
          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_INVERT_MASK | IOCON_PIO_DIGIMODE_MASK | IOCON_PIO_SLEW_MASK | IOCON_PIO_OD_MASK)))

         /* Selects pin function.
          * : PORT022 (pin B12) is configured as USB0_VBUS. */
         | IOCON_PIO_FUNC(PIO022_FUNC_ALT7)

         /* Selects function mode (on-chip pull-up/pull-down resistor control).
          * : Inactive.
          * Inactive (no pull-down/pull-up resistor enabled). */
         | IOCON_PIO_MODE(PIO022_MODE_INACTIVE)

         /* Input polarity.
          * : Disabled.
          * Input function is not inverted. */
         | IOCON_PIO_INVERT(PIO022_INVERT_DISABLED)

         /* Select Analog/Digital mode.
          * : Digital mode. */
         | IOCON_PIO_DIGIMODE(PIO022_DIGIMODE_DIGITAL)

         /* Driver slew rate.
          * : Standard mode, output slew rate control is enabled.
          * More outputs can be switched simultaneously. */
         | IOCON_PIO_SLEW(PIO022_SLEW_STANDARD)

         /* Controls open-drain mode.
          * : Normal.
          * Normal push-pull output. */
         | IOCON_PIO_OD(PIO022_OD_NORMAL));


//    const uint32_t port0_pin29_config = (/* Pin is configured as FC0_RXD_SDA_MOSI */
//                                         IOCON_PIO_FUNC1 |
//                                         /* No addition pin function */
//                                         IOCON_PIO_MODE_INACT |
//                                         /* Input function is not inverted */
//                                         IOCON_PIO_INV_DI |
//                                         /* Enables digital function */
//                                         IOCON_PIO_DIGITAL_EN |
//                                         /* Input filter disabled */
//                                         IOCON_PIO_INPFILT_OFF |
//                                         /* Standard mode, output slew rate control is enabled */
//                                         IOCON_PIO_SLEW_STANDARD |
//                                         /* Open drain is disabled */
//                                         IOCON_PIO_OPENDRAIN_DI);
//    /* PORT0 PIN29 (coords: B13) is configured as FC0_RXD_SDA_MOSI */
//    IOCON_PinMuxSet(IOCON, 0U, 29U, port0_pin29_config);
//
//    const uint32_t port0_pin30_config = (/* Pin is configured as FC0_TXD_SCL_MISO */
//                                         IOCON_PIO_FUNC1 |
//                                         /* No addition pin function */
//                                         IOCON_PIO_MODE_INACT |
//                                         /* Input function is not inverted */
//                                         IOCON_PIO_INV_DI |
//                                         /* Enables digital function */
//                                         IOCON_PIO_DIGITAL_EN |
//                                         /* Input filter disabled */
//                                         IOCON_PIO_INPFILT_OFF |
//                                         /* Standard mode, output slew rate control is enabled */
//                                         IOCON_PIO_SLEW_STANDARD |
//                                         /* Open drain is disabled */
//                                         IOCON_PIO_OPENDRAIN_DI);
//    /* PORT0 PIN30 (coords: A2) is configured as FC0_TXD_SCL_MISO */
//    IOCON_PinMuxSet(IOCON, 0U, 30U, port0_pin30_config);

}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitGT202Shield:
- options: {coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: D2, peripheral: FLEXCOMM8, signal: SCK, pin_signal: PIO3_15/FC8_SCK/SD_WR_PRT}
  - {pin_num: K1, peripheral: FLEXCOMM8, signal: TXD_SCL_MISO, pin_signal: PIO3_17/FC8_TXD_SCL_MISO/SD_D(5)}
  - {pin_num: E1, peripheral: FLEXCOMM8, signal: RXD_SDA_MOSI, pin_signal: PIO3_16/FC8_RXD_SDA_MOSI/SD_D(4)}
  - {pin_num: P11, peripheral: FLEXCOMM8, signal: RTS_SCL_SSEL1, pin_signal: PIO1_22/FC8_RTS_SCL_SSEL1/SD_CMD/CTIMER2_MAT3/SCT0_GPI5/FC4_SSEL3/EMC_CKE(1), identifier: ''}
  - {pin_num: A13, peripheral: GPIO, signal: 'PIO3, 3', pin_signal: PIO3_3/LCD_VD(17)/FC9_TXD_SCL_MISO, direction: OUTPUT, mode: pullDown, invert: disabled}
  - {pin_num: N3, peripheral: GPIO, signal: 'PIO1, 0', pin_signal: PIO1_0/FC0_RTS_SCL_SSEL1/SD_D(3)/CTIMER0_CAP2/SCT0_GPI4/TRACECLK/ADC0_6, direction: INPUT, mode: pullUp,
    invert: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitGT202Shield
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4F */
void BOARD_InitGT202Shield(void)
{
    /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_Gpio1);
    /* Enables the clock for the GPIO3 module */
    CLOCK_EnableClock(kCLOCK_Gpio3);

    gpio_pin_config_t IRQ_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_0 (pin N3)  */
    GPIO_PinInit(BOARD_INITGT202SHIELD_IRQ_GPIO, BOARD_INITGT202SHIELD_IRQ_PORT, BOARD_INITGT202SHIELD_IRQ_PIN, &IRQ_config);

    gpio_pin_config_t PWRON_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_3 (pin A13)  */
    GPIO_PinInit(BOARD_INITGT202SHIELD_PWRON_GPIO, BOARD_INITGT202SHIELD_PWRON_PORT, BOARD_INITGT202SHIELD_PWRON_PIN, &PWRON_config);

    IOCON->PIO[1][0] =
        ((IOCON->PIO[1][0] &
          /* Mask bits to zero which are setting */
          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_ANAMODE_MASK | IOCON_PIO_INVERT_MASK | IOCON_PIO_DIGIMODE_MASK)))

         /* Selects pin function.
          * : PORT10 (pin N3) is configured as PIO1_0. */
         | IOCON_PIO_FUNC(PIO10_FUNC_ALT0)

         /* Selects function mode (on-chip pull-up/pull-down resistor control).
          * : Pull-up.
          * Pull-up resistor enabled. */
         | IOCON_PIO_MODE(PIO10_MODE_PULL_UP)

         /* Enables or disables analog mode.
          * : Disable analog Mode. */
         | IOCON_PIO_ANAMODE(PIO10_ANAMODE_DISABLED)

         /* Input polarity.
          * : Disabled.
          * Input function is not inverted. */
         | IOCON_PIO_INVERT(PIO10_INVERT_DISABLED)

         /* Select Analog/Digital mode.
          * : Digital mode. */
         | IOCON_PIO_DIGIMODE(PIO10_DIGIMODE_DIGITAL));

    IOCON->PIO[1][22] = ((IOCON->PIO[1][22] &
                          /* Mask bits to zero which are setting */
                          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Selects pin function.
                          * : PORT122 (pin P11) is configured as FC8_RTS_SCL_SSEL1. */
                         | IOCON_PIO_FUNC(PIO122_FUNC_ALT1)

                         /* Select Analog/Digital mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO122_DIGIMODE_DIGITAL));

    IOCON->PIO[3][15] = ((IOCON->PIO[3][15] &
                          /* Mask bits to zero which are setting */
                          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Selects pin function.
                          * : PORT315 (pin D2) is configured as FC8_SCK. */
                         | IOCON_PIO_FUNC(PIO315_FUNC_ALT1)

                         /* Select Analog/Digital mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO315_DIGIMODE_DIGITAL));

    IOCON->PIO[3][16] = ((IOCON->PIO[3][16] &
                          /* Mask bits to zero which are setting */
                          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Selects pin function.
                          * : PORT316 (pin E1) is configured as FC8_RXD_SDA_MOSI. */
                         | IOCON_PIO_FUNC(PIO316_FUNC_ALT1)

                         /* Select Analog/Digital mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO316_DIGIMODE_DIGITAL));

    IOCON->PIO[3][17] = ((IOCON->PIO[3][17] &
                          /* Mask bits to zero which are setting */
                          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Selects pin function.
                          * : PORT317 (pin K1) is configured as FC8_TXD_SCL_MISO. */
                         | IOCON_PIO_FUNC(PIO317_FUNC_ALT1)

                         /* Select Analog/Digital mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO317_DIGIMODE_DIGITAL));

    IOCON->PIO[3][3] =
        ((IOCON->PIO[3][3] &
          /* Mask bits to zero which are setting */
          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_INVERT_MASK | IOCON_PIO_DIGIMODE_MASK)))

         /* Selects pin function.
          * : PORT33 (pin A13) is configured as PIO3_3. */
         | IOCON_PIO_FUNC(PIO33_FUNC_ALT0)

         /* Selects function mode (on-chip pull-up/pull-down resistor control).
          * : Pull-down.
          * Pull-down resistor enabled. */
         | IOCON_PIO_MODE(PIO33_MODE_PULL_DOWN)

         /* Input polarity.
          * : Disabled.
          * Input function is not inverted. */
         | IOCON_PIO_INVERT(PIO33_INVERT_DISABLED)

         /* Select Analog/Digital mode.
          * : Digital mode. */
         | IOCON_PIO_DIGIMODE(PIO33_DIGIMODE_DIGITAL));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
